Update expiary date
kushaldas/johnnycanencrypt pull request #69
Opened 2021-07-10 06:44 UTC by kushaldas

Adds `update_expiary_in_subkeys` method for the keystrore.

2021-07-12 02:00 UTC, kushaldas commented
The CI breakage is happening due to:

https://gitlab.com/sequoia-pgp/sequoia/-/issues/701

2021-07-12 18:17 UTC, SaptakS requested changes

2021-07-12 18:17 UTC, SaptakS commented on johnnycanencrypt/__init__.py
> +    def update_expiary_in_subkeys(
The spelling here needs to be `expiry` instead of `expiary`. The same error is there in few other places in this PR that need to be changed.

2021-07-15 13:44 UTC, SaptakS commented on johnnycanencrypt/__init__.py
> +        """Adds a new user id to the given key, saves on the database. Then returns the modified key object
@kushaldas shouldn't this be "Updates the expiration to the given key, saves on the database"?

2021-07-16 07:04 UTC, SaptakS approved these changes
LGTM

2021-07-17 06:04 UTC, merged